### PR TITLE
[Meghana-Step 9] Configure various settings for the app

### PR DESCRIPTION
**Pull request by Meghana-Reddy2**
DESCRIPTION

Standardize the Japanese part
Let's standardize Japanese resources by using Rails' i18n mechanism.
*Converting to i18n has the advantage of making it easier to send messages in later steps.
Setting the time zone
Set the Rails time zone to Japan (Tokyo)
Error page settings
Let's use the default error page provided by Rails as a screen we created ourselves.
Set up error pages appropriately depending on the situation
At least two types of status code settings, 404 page and 500 page, are required.

Screenshot 2024-02-28 at 10 11 18
Screenshot 2024-02-28 at 10 25 38
Screenshot 2024-02-28 at 10 45 51
Screenshot 2024-02-28 at 10 46 03
Screenshot 2024-02-28 at 10 46 32
Screenshot 2024-02-28 at 10 50 26

### CODE REVIEW

**Review by yo-it-engineer — CHANGES_REQUESTED** [review]
`.DS_Store` also can be safely removed from git's tracking. 👍🏻 
They are quite annoying. To deal with them there is a function in git that is called gitignore. Here is some source on it: 
https://www.positioniseverything.net/gitignore-ds_store/

Do you think we can remove both of this file too?
`myapp/myapp/config/locales/en.yml`
and
`myapp/myapp/config/locales/ja.yml`

**Comment by Meghana-Reddy2** [comment]
> `.DS_Store` also can be safely removed from git's tracking. 👍🏻 They are quite annoying. To deal with them there is a function in git that is called gitignore. Here is some source on it: https://www.positioniseverything.net/gitignore-ds_store/
> 
> Do you think we can remove both of this file too? `myapp/myapp/config/locales/en.yml` and `myapp/myapp/config/locales/ja.yml`

**Comment by Meghana-Reddy2** [comment]
Done. Thank you for the material  :)

**Review by yo-it-engineer — APPROVED** [review]
Nice Panda!

LGTM!

**Pull request merged**
