### PR TITLE
[Clover step20] Add label to task

### PR DESCRIPTION
**Pull request by clover-zhao**
### Summary/概要
Description:
Implemented label function to task
Changes Made:

- Add label selection for new task create and update
- Add label column to task detail page
- Modify task index view, task controller and task view to handle search by label

### How to check the behavior/動作確認
- Search by label
    image
- Task create page
    image
- Task detail page
    image

### CODE REVIEW

**Comment by wataru0** [comment]
Can we add a new label?

**Comment by clover-zhao** [comment]
@wataru0 
> Can we add a new label?

Sure! I have refactored the label function so it can add new label:
- New layout
   image
- Input new label and click the button
    image
- New label will show in the label list
    image
- Also able to be attached to the task
    image

**Review by hayashiR1 — APPROVED** [review]
6441099d-2c07-45b5-bc46-bf2b2d8d6a4d

**Comment by wataru0** [comment]
Nicely done 👍

**Pull request merged**
