### PR TITLE
AnneJu step 21: create a maintenance function

### PR DESCRIPTION
**Pull request by anneju**
#### Description
- Let's create a batch to start / end maintenance
- Redirect users who access during maintenance to the maintenance page
- Let's implement it ourselves without using additional gems
- ref: [Step 21: Let's create a maintenance function](https://github.com/Fablic/training/blob/develop/steps_en.md#step-21-lets-create-a-maintenance-function)

#### Stories
- [x] Redirect to maintenance page if mode on
- [x] Write rake tasks to turn on/off the mode 
- [x] Write Specs

#### Related RSpecs
```
rspec myapp/spec/lib/tasks/maintenance_spec.rb myapp/spec/system/tasks_spec.rb:426
```

### CODE REVIEW

**Comment by jeff-yoo-rakuma** [comment]
Please include steps for enabling/disabling maintenance mode!

**Comment by jeff-yoo-rakuma** [comment]
⬆️  Rakuma uses assignee as the PR author

**Comment by anneju** [comment]
@jeff-yoo-rakuma noted~ My last company treat assignee as the "current reviewer", thanks for sharing that~

**Comment by anneju** [comment]
@jeff-yoo-rakuma may I check with you that then how do I assign you to review the PR? Just list you as one of the Reviewers is enough?

**Comment by jeff-yoo-rakuma** [comment]
@anneju Yup that's how we do it. Just put yourself as the assignee and list reviewers on the reviewers section.
We usually need 2 reviewers from the unit and 1 approver(usually Oh-san) for a production release.

**Review by jeff-yoo-rakuma — APPROVED** [review]
LGTM!

**Pull request merged**
