### PR TITLE
Upgrade Ruby to 3.3 and Rails to 7.1

### PR DESCRIPTION
**Pull request by fanfannb**
### Summary
This PR upgrades the Ruby version from 2.6 to 3.3 and the Rails version from 6.0.0 to 7.1. This upgrade is necessary to ensure that new employees can use the latest versions of Ruby and Rails during their training.

### Changes
1. Updated the Ruby version in the Dockerfile
2. Updated the Rails version in the Gemfile.
3.  Updated `docker-compose.yml` to `compose.yml`.
Changed `docker-compose up --build` to `docker-compose up --build`.
Changed `docker-compose run api rails new . --force --database=mysql -G` to `docker compose run api bundle exec rails new . --force --database=mysql -G`
https://qiita.com/mayobimu/items/14d18a354497e830cd55
4. selenium/standalone-chrome:latest is primarily used for x86_64 and will not work properly on ARM devices like the Apple M1 and M2.For Mac M1/M2/M3 users, changed the image in `compose.yml` from `selenium/standalone-chrome:latest` to `seleniarm/standalone-chromium`.
5. In Rails 7.1, the default Dockerfile generated is for the production environment. Changed it to the development environment by adding:
   ```yml
   ENV RAILS_ENV="development"
6. Removed Yarn and Webpacker related code and documentation from the README, as Rails 7.1 no longer uses them.
7. Updated the README to include steps for searching by description.


### I have successfully run the application on my M3 device and another M3 device. If anyone has an M1, M2, or Intel device, please help test to ensure it runs smoothly. Thank you!

### CODE REVIEW

**Comment by mvincent-yap** [comment]
https://github.com/Fablic/training/blob/4c64f062c9f83e359d36bfd29e3617dda42d4e71/steps_jp.md?plain=1#L96-L107

is this still needed? we are not going to use` docker-compose` command because we use `docker compose`

**Review by mvincent-yap — COMMENTED** [review]
tmp files should not be ignored /not be able to commit

**Comment by mvincent-yap** [comment]
I think no need to explain error. just   
   IF m2/3/4 mac do this
       xxxxxx

```dockerコマンド実行したときチップによるエラーが幾つかあります。

no matching manifest for linux/arm64/v8 in the manifest list entries

こういうエラーが出る場合、 docker-compose.ymlのapi:とdb:配下に

platform: linux/amd64

chrome:配下に

image: seleniarm/standalone-chromium

を指定して再実行してください。 参考：[M1 MacによるDocker開発環境構築エラー](https://qiita.com/a-kym/items/10ecb57e0387a673b3a2)

executor failed running [/bin/sh -c apt-get install -y google-chrome-stable]: exit code: 100

こういうエラの場合、Dockerfileを弄って```

**Comment by mvincent-yap** [comment]
why was development gems not installed?
in `docker compose up --build`  log: 
```
Installing turbo-rails 2.0.6
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Gems in the group 'development' were not installed.      <--------------------------
Bundled gems are installed into `/usr/local/bundle`
Post-install message from rubyzip:
RubyZip 3.0 is coming!
```

**Comment by fanfannb** [comment]
> tmp files should not be ignored /not be able to commit

I added a gitignore file

**Comment by fanfannb** [comment]
> https://github.com/Fablic/training/blob/4c64f062c9f83e359d36bfd29e3617dda42d4e71/steps_jp.md?plain=1#L96-L107
> 
> is this still needed? we are not going to use` docker-compose` command because we use `docker compose`

I deleted it

**Comment by fanfannb** [comment]
> I think no need to explain error. just IF m2/3/4 mac do this xxxxxx
> 
> ```
> 
> no matching manifest for linux/arm64/v8 in the manifest list entries
> 
> こういうエラーが出る場合、 docker-compose.ymlのapi:とdb:配下に
> 
> platform: linux/amd64
> 
> chrome:配下に
> 
> image: seleniarm/standalone-chromium
> 
> を指定して再実行してください。 参考：[M1 MacによるDocker開発環境構築エラー](https://qiita.com/a-kym/items/10ecb57e0387a673b3a2)
> 
> executor failed running [/bin/sh -c apt-get install -y google-chrome-stable]: exit code: 100
> 
> こういうエラの場合、Dockerfileを弄って```
> ```

I removed the details of the first error and deleted the second error

**Comment by fanfannb** [comment]
> why was development gems not installed? in `docker compose up --build` log:
> 
> ```
> Installing turbo-rails 2.0.6
> Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
> Gems in the group 'development' were not installed.      <--------------------------
> Bundled gems are installed into `/usr/local/bundle`
> Post-install message from rubyzip:
> RubyZip 3.0 is coming!
> ```

I checked the Gemfile and noticed there isn't a group for production, so I believe that running 'bundle without ' is unnecessary. Therefore, after removing it and verifying the changes, I confirmed that everything runs successfully.

**Review by higuching — APPROVED** [review]
LGTM!

**Comment by mvincent-yap** [comment]
delete log/tmp/config folders

**Comment by fanfannb** [comment]
> delete log/tmp/config folders

I deleted

**Comment by mvincent-yap** [comment]
remove warning

```
❯ docker compose run api bundle exec rails new . --force --database=mysql -G
WARN[0000] /Users/mvincent.yap/Desktop/SOURCE/rakuma/training/myapp/compose.yml: `version` is obsolete 
```

**Comment by mvincent-yap** [comment]
error during build
```
❯ docker compose up --build
WARN[0000] /Users/mvincent.yap/Desktop/SOURCE/rakuma/training/myapp/compose.yml: `version` is obsolete 
[+] Building 1.9s (4/4) FINISHED                                                                                                                  docker:desktop-linux
 => [api internal] load build definition from Dockerfile                                                                                                          0.0s
 => => transferring dockerfile: 1.91kB                                                                                                                            0.0s
 => [api] resolve image config for docker-image://docker.io/docker/dockerfile:1                                                                                   1.6s
 => [api auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                              0.0s
 => CACHED [api] docker-image://docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28                             0.0s
failed to solve: Syntax error - can't find = in "FROM". Must be of the form: name=value
❯ docker compose up --build
```

**Comment by fanfannb** [comment]
> error during build
> 
> ```
> ❯ docker compose up --build
> WARN[0000] /Users/mvincent.yap/Desktop/SOURCE/rakuma/training/myapp/compose.yml: `version` is obsolete 
> [+] Building 1.9s (4/4) FINISHED                                                                                                                  docker:desktop-linux
>  => [api internal] load build definition from Dockerfile                                                                                                          0.0s
>  => => transferring dockerfile: 1.91kB                                                                                                                            0.0s
>  => [api] resolve image config for docker-image://docker.io/docker/dockerfile:1                                                                                   1.6s
>  => [api auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                              0.0s
>  => CACHED [api] docker-image://docker.io/docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28                             0.0s
> failed to solve: Syntax error - can't find = in "FROM". Must be of the form: name=value
> ❯ docker compose up --build
> ```

I didn't get this error, I think maybe you didn't remove the “\” on the previous line when you deleted the BUNDLE_WITHOUT=“development” in the dockerfile.

**Review by mvincent-yap — APPROVED** [review]
LGTM

**Pull request merged**
