### PR TITLE
RoR Training step7: Create pages to create/edit/listing and delete action.

### PR DESCRIPTION
**Pull request by sunao-uehara**
I included adding default RoR files in this PR, so please ignore them for the review, it is really big. And please review the [last commit](https://github.com/Fablic/training/pull/1702/commits/d484c2f30b50f998687c1d63edb935673f6e5a9a) for the step7 updates.

------------------------
I created a controller to handle basic operations such as create/update/delete and show the tasks. It is very minimum spec, no validation, no exception handling..etc as it is not a requirement in this step. I will work on that in latter steps.

> ステップ7: タスクを登録・更新・削除できるようにしよう
タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
rails generate コマンドでコントローラとビューを作成します
コントローラとビューに必要な実装を追加しましょう
作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
routes.rb を編集して、 http://localhost:3000/ でタスクの一覧画面が表示されるようにしましょう

```
#  create controller by following command.
❯ docker-compose run api bundle exec rails g controller Tasks 
...
      create  app/controllers/tasks_controller.rb
      invoke  erb
      create    app/views/tasks
      invoke  test_unit
      create    test/controllers/tasks_controller_test.rb
      invoke  helper
      create    app/helpers/tasks_helper.rb
      invoke    test_unit

# check routing
❯ docker-compose run api bundle exec rails routes -c tasks
   Prefix Verb   URI Pattern               Controller#Action
     root GET    /                         tasks#index
    tasks GET    /tasks(.:format)          tasks#index
          POST   /tasks(.:format)          tasks#create
 new_task GET    /tasks/new(.:format)      tasks#new
edit_task GET    /tasks/:id/edit(.:format) tasks#edit
     task GET    /tasks/:id(.:format)      tasks#show
          PATCH  /tasks/:id(.:format)      tasks#update
          PUT    /tasks/:id(.:format)      tasks#update
          DELETE /tasks/:id(.:format)      tasks#destroy
```

Followings are screenshots for the pages. Task can be created and deleted in this page, and shows the list of tasks.
Also I installed bootstrap to apply very simple styles.

Main
ror_training_step7_main

Details
ror_training_step7_description

Edit
ror_training_step7_edit

Confirmation(flash)
ror_training_step7_edit_confirmation

### CODE REVIEW

**Comment by hayashiR1** [comment]
I think a details screen(詳細画面) is needed in step 7,
Is there any intention to go to the edit screen instead of the detail screen when selecting each task on the task list screen?

**Comment by sunao-uehara** [comment]
> I think a details screen(詳細画面) is needed in step 7, Is there any intention to go to the edit screen instead of the detail screen when selecting each task on the task list screen?

Thank you @hayashiR1 - san for review and the comment. Yes, I combined edit and detail page on purpose just because I thought Edit page is enough to check the detail as well. But for training purpose, I added a detail page and updated PR description as well.

I squashed to combine all step7 related commits here. Could you please check this?.
https://github.com/Fablic/training/pull/1702/commits/d484c2f30b50f998687c1d63edb935673f6e5a9a

**Review by hayashiR1 — APPROVED** [review]
LGTM!
dbea51da-26e7-4126-9866-ff8dd5e6b864

**Comment by sunao-uehara** [comment]
Thanks for the approval. will merge and move on step 8!

**Pull request merged**
