### PR TITLE
Step 13: Add status to make it searchable

### PR DESCRIPTION
**Pull request by taheryasir**
- [x] Add status (not started / started / completed)
- [x] Search tasks by title and status on the list screen
- [x] [Optional requirements] If you are not a beginner, you may install a gem that makes it convenient to implement search such as ransack.
- [x] When narrowing down on searching, let's check the changes in the issued SQL by looking into the log
- [x] Get in the habit of checking up logs as needed in the following steps
- [x] Let's add on the search index on the table
- [x] Let's add a model spec to the search (let's expand the system spec as well)

Task link: https://github.com/Fablic/training/blob/develop_en/README.md#step-13-add-status-to-make-it-searchable

### CODE REVIEW

**Comment by takamizawa-noriaki** [comment]
@taheryasir About "Let's add on the search index on the table'. I can't figure out where did you set the index.
I guess you need to use migration. If I missed something, let me know.

**Comment by takamizawa-noriaki** [comment]
From checklist
- Add status (not started / started / completed)
 -> Can't find out in the pr diff. But somehow you already set enum on the model class.
 https://github.com/Fablic/training/blob/62fcda5c9194bd87380b2f5c2e1015dadc7f8c5a/myapp/app/models/task.rb#L4
- Search tasks by title and status on the list screen
 -> Can't find out in the pr diff.
- [Optional requirements] If you are not a beginner, you may install a gem that makes it convenient to implement search such as ransack.
 -> OK
- Let's add on the search index on the table
 -> Check again
- Let's add a model spec to the search (let's expand the system spec as well)
 -> OK

Maybe OK
 - When narrowing down on searching, let's check the changes in the issued SQL by looking into the log
 - Get in the habit of checking up logs as needed in the following steps

**Comment by taheryasir** [comment]
> Can't find out in the pr diff. But somehow you already set enum on the model class.

I added status before i started this step, so it's already exist when came to this step.

> Let's add on the search index on the table

Maybe i misunderstood this part, isn't by index you meant to add index of tasks in the table when showing tasks? something like below

1. task_ name status label
2. task_name status label

**Comment by takamizawa-noriaki** [comment]
> oh ok so i need to add status into the table

You can add index by using migration. 
FYI: https://stackoverflow.com/questions/15881749/rails-adding-an-index-after-adding-column/15881833

**Comment by takamizawa-noriaki** [comment]
@taheryasir Thanks for adding configuration.
LGTM

**Review by takamizawa-noriaki — APPROVED** [review]
GJ! Well-done!

**Pull request merged**
